server:
  port: 8080

spring:
  application:
    name: task-management-api

  datasource:
    url: jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      continue-on-error: true
jwt:
  secret: F0JSrmdf8uzgL9mQnNxy87lJG7f5ySDtzXnG4bp+yoM=
  expiration: 3600000
logging:
  level:
    org.springframework.security: DEBUG